server:
  port: 5001

mysql:
  type: 'mysql'
  port: 3306

postgres:
  type: 'postgres'
  port: 5432

jwt:
  accessExpiresIn: '30min'
  refreshExpiresIn: '6h'

flask:
  port: 5000
  username: 'back_server'
  password: 'back!Password123!'
